repos:
  - repo: local
    hooks:
      - id: biome-check
        name: biome check
        entry: bunx biome check --write --files-ignore-unknown=true --no-errors-on-unmatched
        language: system
        types: [text]
        pass_filenames: true
