/** Central tuning surface for Card candidate retrieval and reranking. */
export const RETRIEVAL_TUNING = {
  candidates: {
    multiplier: 4,
    minimum: 20,
  },
  query: {
    maxTokens: 12,
    aliases: new Map([["refelction", "reflection"]]),
    ignoredTerms: new Set([
      "a",
      "an",
      "the",
      "and",
      "or",
      "but",
      "if",
      "then",
      "else",
      "at",
      "by",
      "for",
      "with",
      "from",
      "into",
      "to",
      "of",
      "in",
      "on",
      "is",
      "are",
      "was",
      "were",
      "be",
      "been",
      "being",
      "have",
      "has",
      "had",
      "do",
      "does",
      "did",
      "it",
      "its",
      "this",
      "that",
      "these",
      "those",
      "i",
      "you",
      "he",
      "she",
      "we",
      "they",
      "me",
      "my",
      "your",
      "our",
      "can",
      "will",
      "would",
      "could",
      "should",
      "may",
      "might",
      "please",
      "how",
      "what",
      "which",
      "who",
      "why",
      "where",
      "not",
      "no",
      "so",
      "just",
      "also",
      "than",
      "too",
      "very",
      "check",
      "current",
      "currently",
      "generate",
      "generated",
      "generates",
      "relevant",
      "review",
      // Ubiquitous Muton vocabulary carries no retrieval signal inside a Card store.
      "muton",
      "card",
      "cards",
      "session",
      "sessions",
      "http",
      "https",
      "www",
    ]),
  },
  ranking: {
    distinctiveTermMinLength: 5,
    multiTermThreshold: 2,
    multiTermMinMatches: 2,
    bodyOnlyMinMatches: 2,
    titleBoost: 2,
    useWhenBoost: 1.5,
    matchBoost: 1,
    recencyBoost: 0.5,
    recencyWindowDays: 365,
  },
} as const;
